apiVersion: v2
name: edgelessdb
description: EdgelessDB is a MySQL-compatible database for confidential computing. It runs entirely inside a secure enclave and comes with advanced features for collaboration, recovery, and access control.
keywords:
  - database
  - confidential-computing
type: application
appVersion: v0.3.2
version: v0.3.2
maintainers:
  - name: Edgeless Systems
    email: contact@edgeless.systems
    url: https://edgeless.systems/
sources:
  - https://github.com/edgelesssys/edgelessdb
home: https://edgeless.systems
icon: https://raw.githubusercontent.com/edgelesssys/helm/main/edgelessdb_icon.svg
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/edgelesssys/edgelessdb/tree/main/charts
